 python precompute_training_inputs/build_data.py
 python precompute_training_inputs/build_crops.py
 python precompute_training_inputs/build_projindices.py
 python precompute_training_inputs/build_projindices_2.py