_BASE_: "Base-C2_L_R5021k_640b64_4x.yaml"
MODEL:
  DYNAMIC_CLASSIFIER: False
  ROI_BOX_HEAD:
    USE_ZEROSHOT_CLS: True
    IMAGE_LABEL_LOSS: 'max_size'
    # ZEROSHOT_WEIGHT_PATH: 'datasets/metadata/lvis-21k_clip_a+cname.npy'
    ZEROSHOT_WEIGHT_PATH: "datasets/metadata/mp3d_clip.npy"
    USE_FED_LOSS: False # Federated loss is enabled when DYNAMIC_CLASSIFIER is on
  ROI_HEADS:
    # NUM_CLASSES: 22047
    NUM_CLASSES: 20
  WEIGHTS: "output/Detic/BoxSup-C2_LCOCO_CLIP_R5021k_640b64_4x/model_final.pth"
  RESET_CLS_TESTS: True
  TEST_CLASSIFIERS: ("datasets/metadata/mp3d_clip.npy",)
  TEST_NUM_CLASSES: [20,]
SOLVER:
  MAX_ITER: 10000
  IMS_PER_BATCH: 16
  CHECKPOINT_PERIOD: 1000
  # BASE_LR: 0.0001
  BASE_LR: 0.00001
  # WARMUP_ITERS: 1000
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 0.001
DATASETS:
  # TRAIN: ("lvis_v1_train+coco","imagenet_lvis-22k")
  TRAIN: ("mp3d_train",)
  # TEST: ('oid_val_expanded', 'objects365_v2_val')
  TEST: ("mp3d_val",)
DATALOADER:
  # set to TrainingSampler to disable multi-dataset sampling
  SAMPLER_TRAIN: "TrainingSampler"
  # SAMPLER_TRAIN: "MultiDatasetSampler"
  DATASET_RATIO: [1, 4]
  USE_DIFF_BS_SIZE: True
  DATASET_BS: [4, 16]
  DATASET_INPUT_SIZE: [640, 320]
  USE_RFS: [True, False]
  DATASET_INPUT_SCALE: [[0.1, 2.0], [0.5, 1.5]]
  FILTER_EMPTY_ANNOTATIONS: False
  MULTI_DATASET_GROUPING: True
  DATASET_ANN: ['box', 'image']
  NUM_WORKERS: 2
  USE_TAR_DATASET: True
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: ResizeShortestEdge
  MAX_SIZE_TRAIN: 640
  MAX_SIZE_TEST: 640
TEST:
  EVAL_PERIOD: 1000
WITH_IMAGE_LABELS: False